CREATE TABLE IF NOT EXISTS books (
  id SERIAL PRIMARY KEY,
  author VARCHAR(256),
  title VARCHAR(256),
  isbn BIGINT,
  image_url VARCHAR(256),
  description TEXT
);


INSERT INTO books (author, title, isbn, image_url, description) VALUES ('John Ronald Reuel Tolkien', 'The Fellowship of the Ring', '9780007522903', 'http://books.google.com/books/content?id=f3q6mwEACAAJ&printsec=frontcover&img=1&zoom=5&source=gbs_api', 'Fantasy fiction. When they were first published, THE HOBBIT and THE LORD OF THE RINGS became instant classics. Treasured by readers young and old, these works of sweeping fantasy, steeped in unrivalled magic and otherworldliness have sold more than 150 million copies around the world. This new boxed set contains both titles and features brand new cover designs. It offers readers a new opportunity to discover Tolkien''s remarkable world of Middle-earth and to follow the complete story of Bilbo Baggins and the Hobbits'' part in the epic quest for the Ring beginning with Bilbo''s fateful visit from Gandalf and culminating in the dramatic climax between Frodo and Gollum atop Mount Doom.');


INSERT INTO books (author, title, isbn, image_url, description) VALUES ('Patrick Rothfuss', 'The Name of the Wind', '9780575087057', 'http://books.google.com/books/content?id=BcG2dVRXKukC&printsec=frontcover&img=1&zoom=5&source=gbs_api', 'I have stolen princesses back from sleeping barrow kings. I burned down the town of Trebon. I have spent the night with Felurian and left with both my sanity and my life. I was expelled from the University at a younger age than most people are allowed in. I tread paths by moonlight that others fear to speak of during day. I have talked to Gods, loved women, and written songs that make the minstrels weep. My name is Kvothe. You may have heard of me. So begins the tale of Kvothe - currently known as Kote, the unassuming innkeepter - from his childhood in a troupe of traveling players, through his years spent as a near-feral orphan in a crime-riddled city, to his daringly brazen yet successful bid to enter a difficult and dangerous school of magic. In these pages you will come to know Kvothe the notorious magician, the accomplished thief, the masterful musician, the dragon-slayer, the legend-hunter, the lover, the thief and the infamous assassin. The Name of the Wind is fantasy at its very best, and an astounding must-read title.' );

INSERT INTO books (author, title, isbn, image_url, description) VALUES ('William Golding', 'Lord of the Flies', '9781101993224', 'http://books.google.com/books/content?id=r6eoCwAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api', 'William Golding’s unforgettable classic of boyhood adventure and the savagery of humanity comes to Penguin Classics in a stunning Graphic Deluxe Edition with a new foreword by Lois Lowry As provocative today as when it was first published in 1954, Lord of the Flies continues to ignite passionate debate with its startling, brutal portrait of human nature. William Golding’s compelling story about a group of very ordinary boys marooned on a coral island has been labeled a parable, an allegory, a myth, a morality tale, a parody, a political treatise, and even a vision of the apocalypse. But above all, it has earned its place as one of the indisputable classics of the twentieth century for readers of any age. This Penguin Classics Graphic Deluxe Edition features an array of special features to supplement the novel, including a foreword by Lois Lowry, an introduction by Stephen King, an essay by E. M. Forster, an essay on teaching and reading the novel and suggestions for further exploration by scholar Jennifer Buehler, and an extended note by E. L. Epstein, the publisher of the first American paperback edition of Lord of the Flies. For more than seventy years, Penguin has been the leading publisher of classic literature in the English-speaking world. With more than 1,700 titles, Penguin Classics represents a global bookshelf of the best works throughout history and across genres and disciplines. Readers trust the series to provide authoritative texts enhanced by introductions and notes by distinguished scholars and contemporary authors, as well as up-to-date translations by award-winning translators. From the Trade Paperback edition.');

INSERT INTO books (author, title, isbn, image_url, description) VALUES ('George R. R. Martin', 'A Game of Thrones', '9780553386790', 'http://books.google.com/books/content?id=hXNvadj27ekC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api', 'The kingdom of the royal Stark family faces its ultimate challenge in the onset of a generation-long winter, the poisonous plots of the rival Lannisters, the emergence of the Neverborn demons, and the arrival of barbarian hordes.');

INSERT INTO books (author, title, isbn, image_url, description) VALUES ('Dr. Seuss', 'The Cat in the Hat', '9780449810866', 'http://books.google.com/books/content?id=VTu8i9vGUksC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api', 'Two children sitting at home on a rainy day are visited by the Cat in the Hat, who shows them some tricks and games.');